<?xml version="1.0"?>
<robot name="covidrobot" xmlns:xacro="http://ros.org/wiki/xacro">
  <!--Robot common length params-->
  <xacro:property name="base_width" value="0.51"/>
  <xacro:property name="base_height" value="0.25"/>
  <xacro:property name="base_length" value="0.4"/>
  <xacro:property name="robot_height" value="0.15"/>
  <!--Height from bottom surface to floor-->
  <xacro:property name="wheel_dia" value="0.34"/>
  <xacro:property name="fr_wheel_dia" value="0.2"/>
  <xacro:property name="frbox_height" value="${base_height * 0.5}"/>
  <xacro:property name="frbox_length" value="${base_length * 0.5}"/>
  <xacro:property name="pi" value="3.1415" />

  <!--Colour props-->
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>

  <material name="cyan">
    <color rgba="0 0.8 0.8 1"/>
  </material>

  <material name="purple">
    <color rgba="0.8 0 0.8 1"/>
  </material>

  <material name="green">
    <color rgba="0.0 1.0 0.0 1.0"/>
  </material>

  <material name="grey">
    <color rgba="0.2 0.2 0.2 1.0"/>
  </material>

  <material name="orange">
    <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
  </material>

  <material name="brown">
    <color rgba="${222/255} ${207/255} ${195/255} 1.0"/>
  </material>

  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

  <!--Base Component Fixed Start-->
  <link name="base_link">
    <collision>
      <geometry>
        <box size = "0.1 0.1 0.1"/>
      </geometry>
    </collision>
  </link>

  <link name="base_plate">
    <visual>
      <origin xyz="${base_width} ${-base_length+0.2} ${-base_height-0.012}"/>
      <geometry>
        <mesh filename="package://rovit_navsys/meshes/PlanedBase.stl" scale="0.001 .001 .001"/>
      </geometry>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size = "${base_width} ${base_length} ${base_height}"/>
      </geometry>
    </collision>
  </link>

  <link name="imu_link">
    <collision>
      <geometry>
        <box size="0.016 0.031 0.003"/>
      </geometry>
    </collision>
    <visual>
      <geometry>
        <box size="0.016 0.031 0.003"/>
      </geometry>
    </visual>
  </link>

  <joint name="laser_to_imu" type="fixed">
    <parent link="laser_link"/>
    <child link="imu_link"/>
    <origin xyz="-0.08 0 -.025" rpy="${pi} 0 0"/>
  </joint>

  <joint name="base_to_plate" type="fixed">
    <parent link="base_link"/>
    <child link="base_plate"/>
    <origin xyz="0 0 ${base_height*0.5+0.12}" rpy="0 0 ${pi*-0.5}"/>
  </joint>

  <joint name="base_to_laser" type="fixed">
    <parent link="base_plate"/>
    <child link="laser_link"/>
    <origin xyz="0.02 0.31 0.17" rpy="0 0 ${pi*0.5}"/>
  </joint>

  <link name="laser_link">
    <visual>
      <origin xyz="-0.06 0.03 0" rpy="${pi*0.5} 0 0"/>
      <geometry>
          <mesh filename="package://rovit_navsys/meshes/rplidar_main.STL" scale="0.001 .001 .001"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size = "0.09 0.06 .05"/>
      </geometry>
    </collision>
  </link>

  <joint name="base_to_front_box" type="fixed">
    <parent link="base_plate"/>
    <child link="front_box"/>
    <origin xyz="0 0.3 0.05"/>
  </joint>

  <link name="front_box">
    <collision>
      <geometry>
        <box size = "${base_width} ${frbox_length} ${frbox_height}"/>
      </geometry>
    </collision>
  </link>

  <!--Base Component Fixed End-->
  <!--Wheel Components Start-->

  <joint name="roda_kanan" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="base_plate"/>
    <child link="roda_kanan"/>
    <origin rpy="0 ${pi*0.5} 0" xyz="${(base_width * 0.5) + 0.05} -0.1 -0.085"/>
    <limit effort="100" velocity="100"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="roda_kanan">
    <visual>
      <origin rpy="0 ${pi*0.5} 0" xyz="0 0 0.02"/>
      <geometry>
          <mesh filename="package://rovit_navsys/meshes/wheel.stl" scale="0.001 .001 .001"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="${wheel_dia * 0.5}"/>
      </geometry>
    </collision>
  </link>

  <joint name="roda_kiri" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="base_plate"/>
    <child link="roda_kiri"/>
    <origin rpy="0 ${pi*0.5} 0" xyz="-${(base_width * 0.5) + 0.05} -0.1 -0.085"/>
    <limit effort="100" velocity="100"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="roda_kiri">
    <visual>
      <origin rpy="0 ${pi*0.5} 0" xyz="0 0 0.04"/>
      <geometry>
          <mesh filename="package://rovit_navsys/meshes/wheel.stl" scale="0.001 .001 .001"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="${wheel_dia * 0.5}"/>
      </geometry>
    </collision>
  </link>

  <joint name="front_to_kemudi_kanan" type="revolute">
    <axis xyz="0 0 1"/>
    <parent link="front_box"/>
    <child link="kemudi_roda_kanan"/>
    <origin rpy="-0.16 0 0" xyz="0.21 0.11 -0.1"/>
    <limit effort="1" lower="-10" upper="10" velocity="0.1" />
  </joint>

  <link name="kemudi_roda_kanan">
    <visual>
      <origin rpy="0 ${-pi*0.5} ${pi}" xyz="0 0 0.15"/>
      <geometry>
          <mesh filename="package://rovit_navsys/meshes/caster.stl" scale="0.0001 .0001 .0001"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.15" radius="${wheel_dia * 0.06}"/>
      </geometry>
    </collision>
  </link>

  <joint name="front_to_kemudi_kiri" type="revolute">
    <axis xyz="0 0 1"/>
    <parent link="front_box"/>
    <child link="kemudi_roda_kiri"/>
    <origin rpy="-0.16 0 0" xyz="-0.21 0.11 -0.1"/>
    <limit effort="1" lower="-10" upper="10" velocity="0.1" />
  </joint>

  <link name="kemudi_roda_kiri">
    <visual>
      <origin rpy="0 ${-pi*0.5} ${pi}" xyz="0 0 0.15"/>
      <geometry>
          <mesh filename="package://rovit_navsys/meshes/caster.stl" scale="0.0001 .0001 .0001"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.15" radius="${wheel_dia * 0.06}"/>
      </geometry>
    </collision>
  </link>

  <joint name="roda_kiri_depan" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="kemudi_roda_kiri"/>
    <child link="roda_kiri_depan"/>
    <origin rpy="0 ${pi*0.5} 0" xyz="-0.05 0 -0.085"/>
    <limit effort="100" velocity="100"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="roda_kiri_depan">
    <collision>
      <geometry>
        <cylinder length="0.05" radius="${fr_wheel_dia * 0.5}"/>
      </geometry>
    </collision>
  </link>

  <joint name="roda_kanan_depan" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="kemudi_roda_kanan"/>
    <child link="roda_kanan_depan"/>
    <origin rpy="0 ${pi*0.5} 0" xyz="0.05 0 -0.085"/>
    <limit effort="100" velocity="100"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="roda_kanan_depan">
    <collision>
      <geometry>
        <cylinder length="0.05" radius="${fr_wheel_dia * 0.5}"/>
      </geometry>
    </collision>
  </link>

</robot>